### ISSUE TITLE
When LFortran fails, show the full error in the log

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran-lsp#34]
Ideally everything that LFortran prints, so that we can debug it.

**Comment by certik** [comment]
Here is what it prints now:
```
[LFortranCLIAccessor][WARN] Failed to parse response: Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x10002571b[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x100014807[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x100008d43[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x10081d09b[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x10081c12f[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x10074b913[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x100522d6f[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x100522fb3[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x10058692f[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x100586cc3[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x100586f9f[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x100588867[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x100588bc7[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x1005892ff[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x100587233[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x10061b2eb[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x100627eff[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x1006476ab[0m
[2m  Binary file "[0m[1m[35m/Users/ondrej/repos/lfortran/src/bin/lfortran[39m[0m[2m", local address: 0x10052dc53[0m
AssertFailed: is_a<T>(*f)

SyntaxError: Unexpected token 'I', "Internal C"... is not valid JSON
    at JSON.parse (<anonymous>)
    at t.showDocumentSymbols (/Users/ondrej/.vscode/extensions/lcompilers.lfortran-lsp-1.0.0/out/server/src/main.js:39:16493)
    at t.onDocumentSymbol (/Users/ondrej/.vscode/extensions/lcompilers.lfortran-lsp-1.0.0/out/server/src/main.js:81:769)
```
So it works.
